version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_task
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mi_red

volumes:
  postgres_data:

networks:
  mi_red:
    driver: bridge
